CREATE SCHEMA IF NOT EXISTS {{ new_schema }};
CREATE OR REPLACE TABLE {{ database_name }}.{{ new_schema }}.SALES_RAW_bronze_test_2
(
    SALE_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    SALE_DATE DATE,
    QUANTITY INT,
    UNIT_PRICE FLOAT,
    STORE_ID VARCHAR,
    _INSERTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
