config-version: 1.0
root-folder: bronze/migrations/scripts
vars:
  database_name: "${{ secrets.SF_DATABASE }}"
create-change-history-table: true
change-history-table: "${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY"
query-tag: "SCHEMACHANGE_DEPLOY_${{ matrix.name | upper }}"
