CREATE SCHEMA IF NOT EXISTS {{ sf_schema_test }};
CREATE OR REPLACE TABLE {{ database_name }}.{{ sf_schema_test }}.SALES_RAW_SILVER_test_new_schema
(
    SALE_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    SALE_DATE DATE,
    QUANTITY INT,
    UNIT_PRICE FLOAT,
    STORE_ID VARCHAR,
    _INSERTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
